[variables]
NIXPACKS_NODE_VERSION = "18"
NODE_ENV = "production"

[phases.install]
cmds = [
  # Install frontend/tooling dependencies (includes Vite + build tooling)
  "npm ci",
  # Install backend runtime dependencies (omit dev-only tools like nodemon)
  "cd server && if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi"
]

[phases.build]
cmds = [
  # Build the frontend bundle and copy it into server/public
  "npm run build",
  # Debug what we have (helpful in logs)
  "echo 'Contents of server/public:' && ls -la server/public || true",
  # Fail build if index.html is still missing so we don’t deploy a broken image
  "test -f server/public/index.html || (echo 'ERROR: server/public/index.html not found after build.' && exit 1)"
]

# Do NOT define [phases.start]; it runs during image build.
[start]
cmd = "npm start"
