
[phases.build]
cmds = [
  "cd client && npm install && npm run build",
  "cd server && npm install",
  "mkdir -p server/public",
  "cp -r client/dist/* server/public/"
]

[phases.start]
cmds = [
  "cd server && npm start"
]

[start]
cmd = "cd server && npm start"
